### ISSUE TITLE
get_reviews not working

### ISSUE THREAD

**Issue by ylemouel** [AnthonyBloomer/tmdbv3api#38]
Dear support, 

I didn't manage to get "get_reviews" for movies working, it worked with movie details.

Thanks for your help.
```

from tmdbv3api import TMDb, Movie

tmdb = TMDb()
tmdb.api_key = '8fec49646ee9396716bf7b0db3ab9cf7'
tmdb.language = 'fr'

movie = Movie()
with open('/Users/ylemouel/PycharmProjects/tmdb/list') as f:
        for line in f:
            m = movie.reviews(line)
            id_movie = line.rstrip('\n')
            result = m.results[0]
            for items in result.items():
                print(result['author'])
```
`AttributeError: 'list' object has no attribute 'results'`

**Comment by AnthonyBloomer** [comment]
Hello @ylemouel, I noticed you have set the language to be **fr** and what I believe could be the issue is that there is no reviews written in French for the movie id provided. Specifying the language to be **en-US** worked in my case:

``` python
from tmdbv3api import TMDb, Movie

tmdb = TMDb()

tmdb.language = "en-US"
tmdb.api_key = 'YOUR_API_KEY'

movie = Movie()

reviews = movie.reviews(111)

for review in reviews:
    print(review.author)
    print(review.content)
```

If changing the language didn't solve this for you, you can also set `tmdb.debug = True` for debugging purpopses when you run into any issues. This should give you some hints into why you're not getting the desired result.

**Comment by ylemouel** [comment]
Thanks, got point, it was the language selection.
Many thanks!
